name: Generate snake animation

on:
  schedule:       # Run every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:   # Allow manual trigger from GitHub UI
  push:                # Trigger on push to main
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Generate snake animation (with contributions grid)
        uses: Platane/snk@v3
        with:
          github_user_name: sumit-maurya18
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
